import requests
from LogErrors.models import ErrorsLogs
import datetime
def mess(message, userId, token):
	try:
		resp = requests.get("https://api.vk.com/method/messages.send?user_id="+userId+"&message="+message+"&access_token="+ token +"&v=5.87")
		return resp
	except Exception as e :
		d = ErrorsLogs(Date = str(datetime.datetime.today().day)+'.'+str(datetime.datetime.today().month)+'.'+str(datetime.datetime.today().year),
							Link = 'hashDehash',
							Error = e)
		d.save()
#access_token=5e8d89707360cb163c5474a02d730b43a2efb0971b8926dce9efb85844a58104d82e7ea329962be920559
#https://api.vk.com/method/messages.send?user_id=227551898&message=hello&access_token=5e8d89707360cb163c5474a02d730b43a2efb0971b8926dce9efb85844a58104d82e7ea329962be920559&v=5.87 
